DROP TABLE IF EXISTS "2022_2023_data";

CREATE TABLE "2022_2023_data" (
    "CRASH_RECORD_ID" VARCHAR NOT NULL,
    "CRASH_DATE" TIMESTAMP NOT NULL,
	"Weekday" VARCHAR NOT NULL,
	"POSTED_SPEED_LIMIT" INTEGER NOT NULL,
	"TRAFFIC_CONTROL_DEVICE" VARCHAR NOT NULL,
	"WEATHER_CONDITION" VARCHAR NOT NULL,
	"LIGHTING_CONDITION" VARCHAR NOT NULL,
	"FIRST_CRASH_TYPE" VARCHAR NOT NULL,
	"ROADWAY_SURFACE_COND" VARCHAR NOT NULL,
	"CRASH_TYPE" VARCHAR NOT NULL,
	"DAMAGE" VARCHAR NOT NULL,
	"PRIM_CONTRIBUTORY_CAUSE" VARCHAR NOT NULL,
	"NUM_UNITS" INTEGER NOT NULL,
	"MOST_SEVERE_INJURY" VARCHAR,
	"INJURIES_TOTAL" DOUBLE PRECISION,
	"INJURIES_FATAL" DOUBLE PRECISION,
	"INJURIES_INCAPACITATING" DOUBLE PRECISION,
	"CRASH_HOUR" INTEGER NOT NULL,
	"CRASH_DAY_OF_WEEK" INTEGER NOT NULL,
	"CRASH_MONTH" INTEGER NOT NULL,
	"LATITUDE" DOUBLE PRECISION,
	"LONGITUDE" DOUBLE PRECISION,
	"CRASH_TIME" VARCHAR NOT NULL
	
);
	
DROP TABLE IF EXISTS "scatter_mapbox_data";

CREATE TABLE "scatter_mapbox_data" (
    "CRASH_RECORD_ID" VARCHAR NOT NULL,
    "CRASH_DATE" TIMESTAMP NOT NULL,
	"Weekday" VARCHAR NOT NULL,
	"POSTED_SPEED_LIMIT" INTEGER NOT NULL,
	"TRAFFIC_CONTROL_DEVICE" VARCHAR NOT NULL,
	"WEATHER_CONDITION" VARCHAR NOT NULL,
	"LIGHTING_CONDITION" VARCHAR NOT NULL,
	"FIRST_CRASH_TYPE" VARCHAR NOT NULL,
	"ROADWAY_SURFACE_COND" VARCHAR NOT NULL,
	"CRASH_TYPE" VARCHAR NOT NULL,
	"DAMAGE" VARCHAR NOT NULL,
	"PRIM_CONTRIBUTORY_CAUSE" VARCHAR NOT NULL,
	"NUM_UNITS" INTEGER NOT NULL,
	"MOST_SEVERE_INJURY" VARCHAR NOT NULL,
	"INJURIES_TOTAL" DOUBLE PRECISION NOT NULL,
	"INJURIES_FATAL" DOUBLE PRECISION NOT NULL,
	"INJURIES_INCAPACITATING" DOUBLE PRECISION NOT NULL,
	"CRASH_HOUR" INTEGER NOT NULL,
	"CRASH_DAY_OF_WEEK" INTEGER NOT NULL,
	"CRASH_MONTH" INTEGER NOT NULL,
	"LATITUDE" DOUBLE PRECISION NOT NULL,
	"LONGITUDE" DOUBLE PRECISION NOT NULL,
	"CRASH_TIME" VARCHAR NOT NULL,
	"CATEGORIES" VARCHAR NOT NULL	
);

SELECT * FROM "scatter_mapbox_data";
	